### ISSUE TITLE
Investigate use of YAML for config files

### ISSUE THREAD

**Issue by supernova32** [AlloyCI/alloy_ci#24]
Word around the interwebs is that JSON is bad for config files, and YAML is good.

Not sure about that, but if people are really vocal about it, we should at least investigate.

**Comment by hunterboerner** [comment]
I'd be weary of YAML. I used it for a while in https://github.com/rabbit-ci/rabbit-ci but it quickly became a pain to work with in Elixir. It's nice as a human-readable format but absolutely nasty from an implementation perspective. TOML is another option, Elixir support isn't the best but I created this tiny program in Rust to convert between TOML and JSON https://github.com/rabbit-ci/toml2json. Rust has fantastic TOML support because it's used by the build system that comes with the language. The rust program should compile fine for all OSes that Rust supports.

**Comment by tehnomaag** [comment]
Maybe also look at [HCL](https://github.com/hashicorp/hcl) (used in all of Hashicorp products, Terraform, Consul etc). There seems to be [exhcl](https://github.com/asakura/exhcl) available at least.

**Comment by supernova32** [comment]
Thanks for your suggestions @hunterboerner and @tehnomaag. I think you are right, YAML it's not worth the hassle, just to make the configuration file a bit more readable. JSON is perfectly readable as it is, and a breeze to work with in Elixir.

I have looked at TOML before, given that the GitLab Runner uses that for configuration as well. If native support for it in Elixir is not up to par yet, I'll stay away from it until it is. I don't want to add an extra language dependency just to use TOML for the configuration file.

**Comment by supernova32** [comment]
Might be worth revisiting now that `yamerl` v0.7.0 added support for spec 1.2 of YAML and I added the changes necessary to `yaml_elixir` in order for aliases to be properly supported. 

https://github.com/AlloyCI/yaml-elixir

**Comment by supernova32** [comment]
Will implement YAML support with v0.7.0 and deprecate the JSON format. The main reason behind this decision is that YAML is much more flexible than JSON. It allows us to use aliases in oder to avoid  duplication, to add comments to make the config file more understandable, and it is the de facto standard configuration file  for almost all CI systems in the market.
