### ISSUE TITLE
Rename all occurrences of `integration_id` to `app_id`

### ISSUE THREAD

**Issue by vinhnglx** [AlloyCI/alloy_ci#27]
I'm following the [AlloyCI Documentation](https://github.com/AlloyCI/alloy_ci/tree/master/doc) to setup Alloy CI on Docker. When I create a new GitHub App, I found this link: https://developer.github.com/v3/apps/#deprecation-notice-integration_id. 

So, If you're writing new API client code (or updating your existing code), use `app_id` instead of `integration_id`. The `app_id` object contains the same information as `integration_id`.

When I finish setting up the CI with the `app_id`, I will update the Documentation as a new PR.

**Comment by supernova32** [comment]
thanks @vinhnglx. yes, I heard about the change after GitHub decided to change the name (and AlloyCI around 60% of what it is today). Most of the references to `integration_id` are found in the docs, but there are some instances in the code that also need to be changed. The good thing is that it's just naming, since internally the API integration uses the correct arguments.

I would really appreciate a PR if you are up for it 😄
